# Generated by Django 3.0.8 on 2020-07-23 05:26

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import userApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_img', models.ImageField(blank=True, null=True, upload_to=userApp.models.ListUsers.change_filename_avatar, verbose_name='Аватар')),
                ('premium_account', models.BooleanField(default=False, verbose_name='Премиум акк')),
                ('tests_accomplishment_json', jsonfield.fields.JSONField(blank=True, verbose_name='ID_тест:ID_вопрос:выполнено #JSON')),
                ('tests_success_json', jsonfield.fields.JSONField(blank=True, verbose_name='ID_тест:кол-во True')),
                ('preferences_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), default=list, size=None, verbose_name='[Тэг]')),
                ('dictionary_json', jsonfield.fields.JSONField(blank=True, verbose_name='Слово:статус #JSON')),
                ('date_registration', models.DateField(default=datetime.date.today, verbose_name='Дата рег-ции')),
                ('dates_visit_json', jsonfield.fields.JSONField(blank=True, help_text='Даты посещений', verbose_name='дата:test #JSON')),
                ('faq_json', jsonfield.fields.JSONField(blank=True, help_text='FAQ', verbose_name='дата:FAQtext #JSON')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Список служебных данных пользователей',
            },
        ),
    ]
