# Generated by Django 3.0.8 on 2020-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listusers',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
